#!/bin/bash

set -e

mkdir -p ~/tsd/shelly30

while true
do
  (
  F=$(date +%s).json

  curl -s http://192.168.12.30/rpc/Shelly.GetStatus > $$.tmp
  mv $$.tmp ~/tsd/shelly30/$F
  )

  ./docharts
  find ~/tsd/ -type f -mmin +1500 | xargs rm
  sleep 30
done
